# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Operator Controller documentation
theme:
 name: "material"

repo_url: https://github.com/operator-framework/operator-controller

nav: 
  - Home: 'index.md'
  - Components: 'components.md'
  - Tasks: 
    - Adding a catalog of operators: 'adding-a-catalog.md'
    - Explore operators available for installation: 'explore-available-packages.md'
    - Installing an operator: 'installing-an-operator.md'
    - Deleting an operator: 'deleting-an-operator.md'
